#!/usr/bin/env node
/**
 * OpenInverter Extension Build Script
 * 
 * This script concatenates all source modules in src/ into a single OpenInverter.js file
 * for distribution via the Scripto Studio registry.
 * 
 * Usage:
 *   node OpenInverter.build.js
 * 
 * The script will:
 * 1. Read the config block from OpenInverter.js
 * 2. Concatenate all src/** modules in dependency order
 * 3. Write the result back to OpenInverter.js
 */

const fs = require('fs');
const path = require('path');

// Source files in dependency order (utils first, then components, then tabs, then main)
const SOURCE_FILES = [
  'utils/formatting.js',
  'utils/oiHelpers.js',
  'utils/spotValueManager.js',
  'components/DeviceCard.js',
  'components/TabsContainer.js',
  'components/DataTable.js',
  'tabs/DeviceSelectorTab.js',
  'tabs/ParametersTab.js',
  'tabs/SpotValuesTab.js',
  'tabs/CanMappingsTab.js',
  'tabs/CanMessagesTab.js',
  'tabs/OtaUpdateTab.js',
  'main.js'
];

const CONFIG_START_MARKER = '// === START_EXTENSION_CONFIG ===';
const CONFIG_END_MARKER = '// === END_EXTENSION_CONFIG ===';
const BUILD_MARKER = '// === BUILT FROM src/ ===';

function build() {
  const baseDir = __dirname;
  const srcDir = path.join(baseDir, 'src');
  const outputFile = path.join(baseDir, 'OpenInverter.js');
  
  console.log('[Build] Starting OpenInverter extension build...');
  
  // Read config block from existing OpenInverter.js (if it exists)
  let configBlock = '';
  if (fs.existsSync(outputFile)) {
    const existingContent = fs.readFileSync(outputFile, 'utf8');
    const configStart = existingContent.indexOf(CONFIG_START_MARKER);
    const configEnd = existingContent.indexOf(CONFIG_END_MARKER);
    
    if (configStart !== -1 && configEnd !== -1) {
      configBlock = existingContent.substring(configStart, configEnd + CONFIG_END_MARKER.length);
      console.log('[Build] ✓ Preserved extension config block');
    } else {
      console.error('[Build] ✗ No config block found in existing OpenInverter.js');
      process.exit(1);
    }
  } else {
    console.error('[Build] ✗ OpenInverter.js not found');
    console.error('[Build]   Please ensure OpenInverter.js exists with config block');
    process.exit(1);
  }
  
  // Build concatenated output
  let output = configBlock + '\n\n';
  output += BUILD_MARKER + '\n';
  output += '// This file is auto-generated from src/ modules\n';
  output += '// DO NOT EDIT THIS FILE DIRECTLY - Edit files in src/ instead\n';
  output += `// Built: ${new Date().toISOString()}\n\n`;
  
  // Concatenate all source files
  let filesProcessed = 0;
  let filesSkipped = 0;
  
  for (const file of SOURCE_FILES) {
    const filePath = path.join(srcDir, file);
    
    if (!fs.existsSync(filePath)) {
      console.log(`[Build] ⊘ Skipping ${file} (not found yet)`);
      filesSkipped++;
      continue;
    }
    
    const content = fs.readFileSync(filePath, 'utf8');
    output += `// ============================================================================\n`;
    output += `// ${file}\n`;
    output += `// ============================================================================\n\n`;
    output += content;
    output += '\n\n';
    
    filesProcessed++;
    console.log(`[Build] ✓ Concatenated ${file}`);
  }
  
  // Write output
  fs.writeFileSync(outputFile, output, 'utf8');
  
  console.log(`\n[Build] ✓ Built OpenInverter.js`);
  console.log(`[Build]   Files processed: ${filesProcessed}`);
  console.log(`[Build]   Files skipped: ${filesSkipped}`);
  console.log(`[Build]   Output size: ${(output.length / 1024).toFixed(1)} KB`);
  
  if (filesSkipped > 0) {
    console.log(`\n[Build] Note: ${filesSkipped} file(s) not found yet (they will be created in extraction phases)`);
  }
}

// Run build
if (require.main === module) {
  try {
    build();
  } catch (error) {
    console.error('[Build] ✗ Build failed:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

module.exports = { build };
