"""
Headless ZombieVerter Vehicle Module
=====================================

A simulated ZombieVerter VCU for testing without CAN hardware.
Uses the fake_zombieverter simulator to provide realistic metrics.

Perfect for development and testing OVMS extensions without needing
actual TWAI/CAN bus hardware.
"""

# Special protocol identifier for fake simulator
PROTOCOL_FAKE = 'fake'

# Headless Zombie configuration
VEHICLE_CONFIG = {
    'name': 'Headless ZombieVerter (Simulated)',
    'protocol': PROTOCOL_FAKE,  # Uses fake simulator, not real CAN
    'can_tx_id': None,  # Not used
    'can_rx_id': None,  # Not used
    'node_id': None,
    'poll_type': None,
    'metrics': {}  # Metrics are generated by fake_zombieverter.py
}

# No parse functions needed - fake simulator provides ready-to-use data
PARSE_FUNCTIONS = {}

